package com.epam.testauto;

public class Constants {
    public static final String PAGE_URL = "https://jdi-framework.github.io/tests";
    public static final String PAGE_TITLE = "Index Page";
    public static final String USER_NAME = "PITER CHAILOVSKII";
    public static final String HEADER = "EPAM FRAMEWORK WISHES…";
    public static final String MAIN_BLOCK = "LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISICING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMMODO CONSEQUAT DUIS AUTE IRURE DOLOR IN REPREHENDERIT IN VOLUPTATE VELIT ESSE CILLUM DOLORE EU FUGIAT NULLA PARIATUR.";

}
